<?php

namespace Modules\Events\App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Carbon\Carbon;
use Modules\Events\App\Models\Event; 
use Modules\Events\App\Models\Attendee;
use Raziul\Sslcommerz\Facades\Sslcommerz;

class EventRegistrationController extends Controller
{
    /**
     * Show the public event listing or landing page.
     */
    public function index()
    {
        $baseQuery = Event::query()
            ->where('is_active', true)
            ->where('registration_deadline', '>=', now());

        // Safety: ensure only ONE flagship is ever considered (even if DB is dirty)
        $featuredEvent = (clone $baseQuery)
            ->where('is_flagship', true)
            ->orderByDesc('event_date') // newest flagship preferred
            ->first();

        // Exclude featured event explicitly to avoid duplication issues
        $otherEventsQuery = (clone $baseQuery)
            ->where('is_flagship', false);

        if ($featuredEvent) {
            $otherEventsQuery->where('id', '!=', $featuredEvent->id);
        }

        $otherEvents = $otherEventsQuery
            ->orderBy('event_date', 'asc')
            ->get();

        return view('frontend.index', [
            'featuredEvent' => $featuredEvent,
            'otherEvents' => $otherEvents,
        ]);
    }

    /**
     * Show the generic registration form.
     */
    public function show()
    {
        // Fetch only events whose registration deadline is in the future
        $events = Event::where('registration_deadline', '>', now())
                        ->orderBy('event_date', 'asc')
                        ->get();
        
        return view('events::register', compact('events'));
    }

    /**
     * Store a newly created participant registration and initiate payment.
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'event_id' => 'required|exists:events,id',
            'first_name' => 'required|string|max:255',
            'last_name' => 'required|string|max:255',
            'email' => 'required|email|max:255',
            'phone' => 'required|string|max:20',
            
            // IMPORTANT: Parse the strict DD/MM/YYYY format generated by the frontend JS
            'date_of_birth' => 'required|date_format:d/m/Y|before_or_equal:' . now()->subYears(7)->format('d/m/Y'),
            
            'gender' => 'required|in:Male,Female,Other',
            'nationality' => 'nullable|string|max:100',
            'race_category' => 'required|string',
            't_shirt_size' => 'required|string',
            'expected_finish_time' => 'nullable|string',
            'club_or_team' => 'nullable|string',
            'previous_marathons' => 'nullable|integer',
            'blood_group' => 'required|string',
            'medical_conditions' => 'nullable|string',
            'emergency_contact_name' => 'required|string',
            'emergency_contact_phone' => 'required|string',
            'emergency_contact_relation' => 'required|string',
            'address_line' => 'required|string',
            'city' => 'required|string',
            'state_or_district' => 'required|string',
            'postal_code' => 'required|string',
            'country' => 'required|string',
            'photo' => 'required|image|mimes:jpeg,png,jpg|max:5120', // 5MB limit
            'waiver_accepted' => 'accepted',
            'terms_accepted' => 'accepted',
        ], [
            'date_of_birth.date_format' => 'Please enter a valid date in DD/MM/YYYY format.',
            'date_of_birth.before_or_equal' => 'Participants must be at least 7 years old to register.'
        ]);

        // 1. Handle Photo Upload
        if ($request->hasFile('photo')) {
            $path = $request->file('photo')->store('attendee-photos', 'public');
            $validated['photo_path'] = $path;
        }
        
        // Remove the temporary 'photo' key since the DB column is 'photo_path'
        unset($validated['photo']);

        // 2. Parse Age Category & Convert Date for Database
        // We use createFromFormat to safely read the DD/MM/YYYY text
        $dob = Carbon::createFromFormat('d/m/Y', $request->date_of_birth);
        
        // Re-assign the date to the standard SQL YYYY-MM-DD format for insertion
        $validated['date_of_birth'] = $dob->format('Y-m-d');
        
        $age = $dob->age;
        
        if ($age >= 7 && $age <= 10) {
            $validated['age_category'] = '7-10 Infant';
        } elseif ($age > 10 && $age <= 14) {
            $validated['age_category'] = '10-14 Kid';
        } else {
            $validated['age_category'] = 'Adult Runner';
        }

        // 3. Ensure booleans are explicitly formatted for DB insertion
        $validated['waiver_accepted'] = true;
        $validated['terms_accepted'] = true;

        // 4. Set Registration Fee (Pull from Event, or fallback to 1000)
        $event = Event::find($request->event_id);
        $validated['registration_fee'] = $event->base_registration_fee ?? 1000;

        // 5. Generate a Unique Transaction ID and set status to Pending
        $transactionId = 'TRUN_' . strtoupper(uniqid());
        $validated['transaction_id'] = $transactionId;
        $validated['payment_status'] = 'Pending';

        // 6. Create the Attendee
        $attendee = Attendee::create($validated);

        // 7. Initiate SSL Commerz Payment (setAdditionalInfo removed)
        $response = Sslcommerz::setOrder(
            $validated['registration_fee'],          // Amount to charge
            $transactionId,                          // Unique transaction ID
            $event->title . ' - ' . $request->race_category // Product Name (Event + Category)
        )
        ->setCustomer(
            $request->first_name . ' ' . $request->last_name,
            $request->email,
            $request->phone
        )
        ->makePayment();

        // 8. Handle AJAX Response for SSL Commerz Popup
        if ($request->ajax() || $request->wantsJson()) {
            if ($response->success()) {
                return response()->json([
                    'status' => 'success',
                    'GatewayPageURL' => $response->gatewayPageURL()
                ]);
            }
            
            return response()->json([
                'status' => 'error',
                'message' => 'Failed to connect to payment gateway.'
            ], 500);
        }

        // 9. Standard Redirect (Fallback for non-JS browsers)
        if ($response->success()) {
            return redirect($response->gatewayPageURL());
        }

        return back()->withErrors(['error' => 'Payment gateway failed to initialize. Please try again.']);
    }
}